/**
 * Apache / cPanel rules. Built as /htaccess.txt and renamed to /.htaccess after the build
 * (see the "raydana-htaccess" integration in astro.config.mjs).
 * - 301 redirects from the old Persian URLs (/products/…, /services/ …) to the new Persian slugs.
 * - A not-found page per language.
 * The forwarding HTML pages stay in place as a fallback for hosts that ignore .htaccess.
 */
import type { APIRoute } from 'astro';
import { getRoutes, type RedirectRoute } from '../routing';

// Apache matches the decoded path; escape regex characters and match an optional trailing slash.
const pattern = (path: string) => `^${path.replace(/^\//, '').replace(/\/$/, '').replace(/[.*+?^${}()|[\]\\-]/g, '\\$&')}/?$`;

export const GET: APIRoute = async () => {
  const redirects = (await getRoutes()).filter((r): r is RedirectRoute => r.kind === 'redirect');
  const rule = (r: RedirectRoute, code: number) => `RewriteRule ${pattern(r.path)} ${encodeURI(r.to)} [R=${code},L,NE]`;
  const legacy = redirects.filter((r) => r.reason === 'legacy').map((r) => rule(r, 301));
  const fallback = redirects.filter((r) => r.reason === 'fallback').map((r) => rule(r, 302));

  const body = `# Generated by src/pages/htaccess.txt.ts — do not edit by hand.
AddDefaultCharset UTF-8
AddType application/xml .xml
DirectoryIndex index.html
ErrorDocument 404 /404.html
<If "%{REQUEST_URI} =~ m#^/en/#">
ErrorDocument 404 /en/404/index.html
</If>
<If "%{REQUEST_URI} =~ m#^/ru/#">
ErrorDocument 404 /ru/404/index.html
</If>
<If "%{REQUEST_URI} =~ m#^/ar/#">
ErrorDocument 404 /ar/404/index.html
</If>

<IfModule mod_rewrite.c>
RewriteEngine On

# Old Persian URLs → new Persian URLs (permanent)
${legacy.join('\n')}
${fallback.length ? `\n# Pages of a language not translated yet → English (temporary)\n${fallback.join('\n')}\n` : ''}</IfModule>
`;
  return new Response(body, { headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
};
